language: python

services:
  - docker

before_install:
  - docker build -t amazeteam/cmpe272assignment -f docker/Dockerfile .

script:
  - docker --version
  - docker run --rm -p 80:80/tcp -v `pwd`/../database:/data/db amazeteam/cmpe272assignment
