language: python

services:
  - docker

jobs:
  include:
    - stage: build_docker_image
      script: 
        - docker --version
        - docker build -t amazeteam/cmpe272assignment -f docker/Dockerfile .
    - stage: do_unit_test
      script:
        - docker run --rm -p 80:80/tcp -v `pwd`/../database:/data/db amazeteam/cmpe272assignment unittest

